---

- apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg2"]
    state: present
    install_recommends: no

- apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present
    filename: docker
  register: repository_added

- apt:
    update_cache: yes
  when: repository_added.changed

- apt:
    name: ["docker-ce"]
    state: present
    force: yes
    install_recommends: no

- service:
    name: docker
    enabled: true
    state: started
